# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=3.0.0
group=me.jaffe2718
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Microphone Text Input
mod_author=Jaffe2718
mod_id=mcmti
license=MIT
credits=
description=Speech recognition chat message input tool for Minecraft.
minecraft_version_range=[1.20.1,1.21)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.7+1.20.1
fabric_loader_version=0.16.14
compatibility_mc_versions=>=1.20.1
compatibility_fabricloader_versions=>=0.15.0
compatibility_midnightlib_versions=>=1.9.0

# Forge
forge_version=47.4.10
forge_loader_version_range=[47,)

# Dependent Mods
midnightlib_version=1.9.1+1.20.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
