package me.jaffe2718.mcmti.event;

public enum EventType {
    SPEECH_RECOGNIZER_REGISTERED,
    SPEECH_RECOGNIZER_ACTIVATED,
    SPEECH_RECOGNIZER_DEACTIVATED,
    SPEECH_RECOGNIZER_TRANSCRIBED,
    ALL_SPEECH_RECOGNIZERS_DEREGISTERED
}
